### ISSUE TITLE
tensorflow:AutoGraph is not available in this environment

### ISSUE THREAD

**Issue by mukeshsnp12** [zhaoyun0071/roop-win-GUI#4]
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.

**Comment by zhaoyun0071** [comment]
> WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.

忽略
